MNGFinal/CafeSync-Back

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/EmployeeDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/FranchiseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/JobDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserDetailsImpl.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Job.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserDetailsServiceImpl.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/a.java

#12 
API 호출 테스트 완료되어 merge 하겠습니다
어떤 변경 사항이 있나요?
<br>

[25.02.13] API 호출 테스트

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dao/UserRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/EmployeeDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/FranchiseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/JobDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Job.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/User.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/a.java

#8 
- 기존 로그인 정보는 단순 PK 값만 가져왔지만 필요한 정보에 대해선 객체로 추가적으로 가져오게끔 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.12] JWT 토큰 로그인정보 추가

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/ScheduleRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/ScheduleDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Schedule.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/ScheduleService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/a.java

#10 
스케줄 관리 조회 구현 진행 중 임시 머지
어떤 변경 사항이 있나요?
<br>

스케줄 관리 조회 구현 진행 중 임시 머지

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/JwtAuthenticationFilter.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java

#12 
시큐리티  설정 일부 수정(임시) API 호출 모두 허용으로 처리해두었습니다 추 후 JWT 검증으로 수정하겠습니다
어떤 변경 사항이 있나요?
<br>

[25.02.13] 시큐리티  설정 일부 수정(임시)

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java

없음
FireBase 이미지 저장 수정, 시큐리티 로직 수정(임시) api 권한 permitAll
어떤 변경 사항이 있나요?
<br>

[25.02.14] 파이어베이스  및 시큐리티 로직 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dao/NoteRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/a.java

7
바리스타노트 전체조회 백엔드 로직
어떤 변경 사항이 있나요?
<br>

백엔드 - [25.02.14] 바리스타노트 전체 조회

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java

36
바리스타 노트 세부조회 및 전체조회 postman
어떤 변경 사항이 있나요?
<br>

[25.02.17] 바리스타 노트 세부 조회 및 전체조회 재확인

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/dao/MenuRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java

- #33 
- sold out 기능
어떤 변경 사항이 있나요?
<br>

[25.02.17] sold out 기능

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java

#39 
- List 타입으로 체크된 모든 재고 수량을 확인 후 업데이트 하도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.18] 재고 수량 업데이트 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dao/NoteRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/AccountDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/EmployeeDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Account.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java

[25.02.18] 바리스타 노트 세부 조회 및 검색기능

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java

#41 
- 체크된 항목만 삭제될 수 있도록 하였습니다
- JPA 에서 기본 제공된 메소드인 deleteAllByIdInBatch 를 사용하여 데이터를 삭제할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.18] 재고 데이터 삭제 기능 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranchiseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/InOut.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java

#48 
- 입출고 데이터 조회 기능이 구현되었습니다
어떤 변경 사항이 있나요?
<br>

[25.02.19] 입출고 데이터 조회 기능 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/dto/UserLoginDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/entity/Franchise.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/model/service/UserService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dto/EmployeeDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/FranService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java

없음
이정님을 위한 백엔드 합치기
어떤 변경 사항이 있나요?
<br>

[25.02.19] 백엔드 합쳐놓기

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java

#53 
스케줄 관리 조회 수정 완료하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.20] 스케줄 관리 조회 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInventoryRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutInventoryRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/InOutRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInventory.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/InOutService.java

#65 
- 입출고 내역의 데잍터 기반으로 출고하는 매장에서 차감과 입고하는 매장의 증가의 로직으로 구현하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.20] 입출고 승인 및 취소 로직 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dao/FranRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dto/FranDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/entity/Fran.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java

- 66
- 프랜차이즈 이미지
어떤 변경 사항이 있나요?
<br>

[25.02.20] 프랜차이즈 이미지

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java

#27 
스케줄 등록 로직 구현하였습니다.
ResponseDTO 적용은 명일 진행하겠습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.20] 스케줄 등록 로직 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/dto/FranDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/entity/Fran.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java

- 87
- 가맹점 등록
어떤 변경 사항이 있나요?
<br>

[25.02.21] 가맹점 등록

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/dto/NoteInsertDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/service/NoteService.java

86
바리스타 노트 삭제 기능
어떤 변경 사항이 있나요?
<br>

[2025-02-21] 바리스타 노트 삭제 기능

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranchiseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDetailDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java

#78 #80 
- ResponseDTO 를 활용하여 상태코드 분리 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.21] 발주 신청 조회, 스웨거 작성

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranInvenDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/FranchiseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutInventoryJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InOutJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/InventoryJoinDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDetailDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/OrderDetail.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java

#90 #91 
- 기존 데이터는 업데이트, 새로운 데이터는 인설트 로직으로 분리하여 저장될 수 있도록 하였습니다
- 서비스단 로직은 기존 데이터의 경우 발주 신청 내역의 고유 키값을 가지고 있어서 식별할 수 있지만
- 새로운 데이터는 발주 신청 내역중에 어디다가 추가해야 할 지 모르기 때문에 이 부분을 신경써서 로직을 구성하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.21] 발주 내역 추가, 수정 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java

#81 
스웨거 명세 설정 작업 완료하였습니다.
기존에 작성한 컨트롤러 내 리턴 타입 변경 작업 완료하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.21] 스웨거 명세 설정 및 리턴 타입 변경 작업

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dao/ScheduleRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java

#27 
스케줄 등록 관련하여 로직 수정하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.21] 스케줄 등록 로직 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/VendorDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/ActDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SummaryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/a.java

#99 
전표 조회 기능이 구현되었습니다
어떤 변경 사항이 있나요?
<br>

[25.02.22] 전표 조회

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/ActController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dao/ActRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/dto/ActDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/entity/Act.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/ActService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/act/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/SlipInsertDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/controller/SummaryController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dao/SummaryRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/dto/SummaryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/entity/Summary.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/SummaryService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/summary/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dao/VendorRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/a.java

#100 #101 
- 만약 기존 데이터 + 새로운 전표 데이터를 저장하려고 하면
- 기존 데이터가 있는 전표는 해당 PK 값을 조회해온 후 업데이트 할 수 있도록 하였습니다
- PK값이 없다면 insert로 할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.23] 전표 추가 및 저장 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java

#101 
- 전표 삭제 기능이 구현되었습니다
어떤 변경 사항이 있나요?
<br>

[25.02.23] 전표 삭제 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlSlipRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/TaxRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlSlipDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/TaxDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Pnl.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/PnlSlip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/PnlService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java

#102 #103 
- 세금 및 손익 계산서 생성이 구현되었습니다
어떤 변경 사항이 있나요?
<br>

[25.02.23] 세금 및 손익계산서 생성 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java

- 109
-  가맹점 삭제
어떤 변경 사항이 있나요?
<br>

[25.02.24] 가맹점 삭제

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/controller/TaxController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/dao/TaxRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java

#121 
- 세금 계산서 삭제 기능이 구현되었습니다
- 체크된 항목만 삭제할 수 있도록 하였습니다
- 세금 계산서 삭제할 시 세금 계산서만 삭제되고 전표 삭제 시 관련된 세금 계산서까지 모두 삭제됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.25] 세금 계산서 삭제

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java

148
공지사항 조회수 새로고침하면 늘어나는 것 막음
전체조회페이지에서 상세조회페이지에 갈때만 조회수는 증가
어떤 변경 사항이 있나요?
<br>

[25.02.25] 공지사항 조회수 새로고침하면 늘어나는 것 막음

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/FranInvenService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/controller/SlipController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/PnlSlipRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dao/SlipRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/dto/PnlSlipDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Pnl.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/PnlSlip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Slip.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/entity/Tax.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/PnlService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/SlipService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/slip/model/service/TaxService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/controller/TaxController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/dao/TaxRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java

#112 
- 가맹점마다 손익 계산서 내용을 확인할 수 있습니다
- 총 수익, 총 비용, 순이익, 이익률 확인이 가능합니다
- 특정 날짜에 대한 필터링도 가능합니다
- PDF 파일로 추출할 수 있도록 하였습니다
- 필요없는 데이터는 삭제할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.25] 손익 계산서 기능 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dao/ScheduleRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java

#123 
스케줄 수정 로직 추가
어떤 변경 사항이 있나요?
<br>

[25.02.25] 스케줄 관리 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/common/ResponseDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dao/NoticeAccountRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dao/NoticeInsertRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/dto/NoticeInsertDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/NoticeInsert.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java

128
공지사항 등록 백엔드
어떤 변경 사항이 있나요?
<br>

[25.02.26] 공지사항등록 

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/service/ScheduleService.java

#123 #139 
스케줄 수정할 때의 PutMapping과 수정 내에서 신규로 등록하는 스케줄에 대한 PostMapping을 조정하였습니다.
스케줄 삭제 요청에 대한 처리 로직을 구현하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.27] 스케줄 수정 및 삭제 기능 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/NoteInsert.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/NoticeInsert.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java

135
공지사항 수정 / 삭제 / 페이지네이션
어떤 변경 사항이 있나요?
<br>

[25.02.27] 공지사항 수정/삭제/페이지네이션

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/entity/Menu.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java

- 144
- 본사 메뉴 삭제
어떤 변경 사항이 있나요?
<br>

[25.02.28] 본사메뉴삭제

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/controller/MenuController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/menu/model/service/MenuService.java

- 150
- 본사 메뉴 등록
어떤 변경 사항이 있나요?
<br>

[25.02.28] 본사 메뉴 등록

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/controller/ScheduleController.java

#148 
집 나갔던 삭제 로직 복구하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.28] 스케줄 삭제 로직 복구

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dto/ComplainDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/dto/ScheduleDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/schedule/model/entity/Schedule.java

#147 
컴플레인 화면에서 기간 조회가 이루어지도록 설정하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.28] 컴플레인 기본 조회 로직

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/controller/VendorController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/dto/VendorDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/entity/Vendor.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/vendor/model/service/VendorService.java

#157 
- 본사 페이지 공급업체 관리 기능이 구현되었습니다
- 신규 업체 등록을 할 수 있습니다
- 이미지 등록 시 구글 클라우드와 Firebase를 연동하여 클라우드 서버에 저장되도록 하였습니다
- 정확한 주소지 입력을 위해 다음 API 주소를 활용하였습니다
- 값을 하나라도 입력하지 않을 시 버튼이 비활성화 됩니다
어떤 변경 사항이 있나요?
<br>

[25.03.04] 공급업체 관리

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/controller/FranController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franchise/model/service/FranService.java

#162 
- 본사 가맹점 관리 수정 및 등록 로직 수정, UI 변경되었습니다
- 수정 및 등록에서 필드값이 하나라도 없다면 등록 및 수정할 수 없도록 하였습니다
- 등록할 때 가맹점 코드는 DB에서 확인 후 없는 가맹점 코드로 부여하는 방향으로 변경 되었습니다
- 사번 코드로 등록하는 것이 아닌 이름으로 등록할 수 있게 UI를 변경하였습니다
- 가맹점 이미지는 Firebase 에 저장할 수 있도록 하였습니다 
- 주소 찾기는 다음 API 를 활용하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.05] 본사 가맹점 관리 구현

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/sales/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/sales/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/sales/model/service/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/controller/StatController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dao/StatRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MonthlySalesDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesDataDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesSummaryDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/StatDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/entity/Stat.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/service/StatService.java

- 156
- 가맹점통계
어떤 변경 사항이 있나요?
<br>

[25.03.05] 가맹점통계

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/dao/EmpRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/entity/Employee.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java

#169 
- 가맹점 직원관리 기능이 구현되었습니다
- 점장 직급일 경우에만 수정 및 신규 직원 등록이 가능합니다
- 바리스타 직급일 경우 버튼이 안보이도록 하였습니다
- 수정이나 등록할 경우 메모 및 퇴사일을 제외한 나머지 필드값을 입력하지 않았으면 등록할 수 없도록 하였습니다
- 주소 변경이나 입력 시 다음 API 사용 하였습니다
- 프로필 이미지는 Firebase에 저장할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.06] 가맹점 직원 관리

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/controller/StatController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dao/StatRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MenuSalesDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/entity/Stat.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/service/StatService.java

- 172
- 가맹점 메뉴별 통계
어떤 변경 사항이 있나요?
<br>

[25.03.06] 가맹점 메뉴별 통계

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/Entity/Complain.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/dao/ComplainRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/model/service/ComplainService.java

#175 
컴플레인 조회 로직 수정
어떤 변경 사항이 있나요?
<br>

[25.03.06] 컴플레인 조회 로직 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/controller/EmpController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/employee/model/service/EmployeeService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/controller/NoteController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/service/NoticeService.java

#178 
- 공지사항, 바리스타 노트 파일 첨부 기능이 추가되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.07] 공지사항, 바리스타 노트 파일첨부 기능 추가

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/note/model/entity/Note.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/controller/NoticeController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/notice/model/entity/Notice.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/MonthlySalesDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesDataDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/stat/model/dto/SalesSummaryDTO.java

없음
- 가맹점 데이터 표현되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.07] 메인화면 데이터 표현하기

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dto/PromotionDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/entity/Promotion.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/a.java

#184 
일정 관리 조회 로직
어떤 변경 사항이 있나요?
<br>

[25.03.07] 일정 관리 조회 로직

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/complain/controller/ComplainController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/Controller.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/a.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dto/PromotionDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/entity/Promotion.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/a.java

#186 
일정 등록
어떤 변경 사항이 있나요?
<br>

[25.03.07] 일정 등록

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/tax/model/service/TaxService.java

- 세금계산서 버그 수정
어떤 변경 사항이 있나요?
<br>

[25.03.08] 세금계산서 버그 수정

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/FranInvenRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dao/OrderRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/dto/OrderDTO.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/entity/FranInven.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/inventory/model/dao/InventoryRepository.java

#190 
- 본사 발주내역 승인 반려 기능이 추가되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.08] 본사 발주내역 승인 반려 추가

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java

[25.03.08] 발주내역 내림차순

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/SecurityConfig.java

#193 
- Redis 에 저장된 RefreshToken을 기반으로 AccessToken 갱신 기능이 추가 되었습니다
- RefreshToken은 발급 후 7일간 Redis 에 보관 AccessToken 은 15분동안 session에 저장 및 유효
어떤 변경 사항이 있나요?
<br>

[25.03.08] 토큰 갱신 기능 추가

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/controller/FranInvenController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java

#195 
- 특정 시간대 발주 신청이 몰릴 상황을 가정하여 트래픽 테스트 후 성능 개선 된 코드로 변경하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.10] 발주 신청 성능 개선

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/franinven/model/service/OrderService.java

#195 
- 발주 신청 트래픽 테스트 후 성능 개선 되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.10] 성능 개선

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/controller/PromotionController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/dao/PromotionRepository.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/promotion/model/service/PromotionService.java

#186 #201 #202 
일정 등록 로직 작성
일정 수정 로직 작성
일정 삭제 로직 작성
어떤 변경 사항이 있나요?
<br>

[25.03.12] 일정 등록, 수정, 삭제

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/account/controller/UserController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/chat/controller/ChatWebSocketController.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/WebSocketConfig.java
CafeSync-FinalProject/src/main/resources/application.yml

[25.03.13] 배포 테스트

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/CorsConfig.java
CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/WebSocketConfig.java

[25.03.13] 배포 테스트 2번째

---

CafeSync-FinalProject/src/main/resources/application.yml

[25.03.13] 배포 테스트 4번째

---

CafeSync-FinalProject/src/main/resources/application.yml

[25.03.13] 배포 테스트 5번째

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RedisConfig.java

[25.03.13] 배포 테스트 14번째

---

CafeSync-FinalProject/src/main/resources/application.yml

[25.03.13] 배포 테스트 16번째

---

CafeSync-FinalProject/src/main/java/com/ohgiraffers/cafesyncfinalproject/config/RedisConfig.java
CafeSync-FinalProject/src/main/resources/application.yml

[25.03.13] 배포 테스트 17번째
